spring:
  application:
    name: marketplace-order-api
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/marketplace}
    username: ${DB_USERNAME:marketplace}
    password: ${DB_PASSWORD:marketplace}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true

server:
  port: ${PORT:8080}

springdoc:
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info
